ke:kehuduan.c
	gcc kehuduan.c -lpthread -o ke
	gcc liaotianshi.c -lpthread -lsqlite3 -o fu
fu:liaotianshi.c
	gcc kehuduan.c -lpthread -o ke
	gcc liaotianshi.c -lpthread -lsqlite3 -o fu
clean:
	rm -f ke fu

